on:
  pull_request_target:
    types: 
      [opened, synchronize, reopened, edited, review_requested, labeled]
    paths:    
      - 'sourceData/**'
jobs:
  gbBotFileChecks:
    runs-on: ubuntu-latest
    container: osgeo/gdal:ubuntu-small-latest
    name: geoBoundary Bot File Checks
    steps:
      - name: Checking File Validity
        uses: wmgeolab/geoBoundaryBot@master
        with:
          check: "file"

  gbBotMetaChecks:
    runs-on: ubuntu-latest
    container: osgeo/gdal:ubuntu-small-latest
    name: geoBoundary Bot Metadata Validity Checks
    steps:
      - name: Checking Metadata Validity
        uses: wmgeolab/geoBoundaryBot@master
        with:
          check: "meta"
  
  gbBotGeometryChecks:
     runs-on: ubuntu-latest
     container: osgeo/gdal:ubuntu-small-latest
     name: geoBoundary Bot Data Technical Validity Checks
     steps:
       - name: Checking Data Technical Validity
         uses: wmgeolab/geoBoundaryBot@master
         with:
           check: "geom"  
    
