on:
  pull_request_target:
    types: 
      [opened, synchronize, reopened, edited, review_requested, labeled]
    paths:    
      - 'sourceData/**'
jobs:
  bCheck:
    runs-on: ubuntu-latest
    container: osgeo/gdal:alpine-ultrasmall-latest
    steps:
    - name: Initialize Linux Environment
      run: |
           apt-get update
           apt-get install -y software-properties-common
           add-apt-repository ppa:git-core/ppa
           apt-get update
           apt-get install -y git
    
    - name: Download Proposed Changes
      uses: actions/checkout@v2.3.2
      with:
        lfs: False
        fetch-depth: 0

    - name: Check for valid files
      run: |
           echo ${GITHUB_SHA}
           echo ${GITHUB_WORKSPACE}
           echo "==============================================="
           git diff-tree --no-commit-id --name-only -r ${{github.sha}} > proposedChanges
           cat proposedChanges
           echo "==============================================="
           python actions/boundaryZipCheck/bZipCheck.py
