on:
  push:
    paths:    
    - 'sourceData/**'
jobs:
  bCheck:
    runs-on: ubuntu-latest
    container: osgeo/gdal:ubuntu-full-latest
    steps:
    - name: Initialize Linux Environment
      run: |
           apt-get update
           apt-get install -y software-properties-common
           add-apt-repository ppa:git-core/ppa
           apt-get update
           apt-get install -y git
    
    - name: Download Proposed Changes
      uses: actions/checkout@v2.3.2
      with:
        lfs: False

    - name: Check for valid files
      run: |
           git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
           git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > proposedChanges
           git show --name-only --pretty=format:
           git show --name-only --pretty=format: > proposedChanges
           cat proposedChanges
           pwd
