on:
  push:
    paths:    
    - 'website/geoDesc/**'
name: geoDesc Website Update

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy geoDesc Node
        uses: appleboy/ssh-action@v0.1.2
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         password: ${{ secrets.SSH_PASSWORD }}
         script: |
               cd geodesc.org
               git clone https://github.com/DanRunfola/gbRelease.git
               cd gbRelease
               git checkout gD
               cd website
               cd geoDesc
               mv * ~/geodesc.org
               cd ~/geodesc.org
               npm install
               export MapboxAccessToken=${{ secrets.MAPBOX }}
               npm start
